service: dazn-coding-challenge

custom:
  settings:
    USER_STREAMS_TABLE: userStreams
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings}
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.USER_STREAMS_TABLE}"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  logStream:
    handler: handler.logStream
    events:
      - http:
          path: /stream
          method: post

resources:
  Resources:
    UserStreamsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "streamId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "streamId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.USER_STREAMS_TABLE}
